### PR TITLE
github/workflows (nightly): Add check for macOS

### PR DESCRIPTION
**Pull request by aiotter**
This PR is a suggestion to introduce `make check` in macOS as well as Ubuntu.
There is some errors occurring and I don't know they should be fixed.
Feel free to close this if the current errors are hard to fix, or should not be fixed by any other reasons.

### CODE REVIEW

**Comment by akinomyoga** [comment]
FYI, I actually had a similar branch in my local repository (which hadn't pushed to GitHub). Now, I have pushed it 451579fd69ccd07bbb1478cce54527fde36639a3. At that time, I decided to not merge it in the master because I didn't like it affecting the clone stats of GitHub.

> There is some errors occurring and I don't know they should be fixed. Feel free to close this if the current errors are hard to fix, or should not be fixed by any other reasons.

Hmm, it's hard to decide for me at the moment because I don't know either how the errors come out. The first error is easy. It's just because of some delay in macOS. The function supposed to wait for the specified time duration (100ms in the test), but somehow the delay is too large in macOS. For this error, I think maybe we can loosen the acceptable delay.

The second and the third errors seem to be the identical issue, but I'm not sure why they fail. I don't have macOS so cannot test it in local environments. Later, maybe I try to figure it out by pushing some experimental commits to this PR. Or, I'd appreciate it if you could take time to investigate it.

**Comment by aiotter** [comment]
> Later, maybe I try to figure it out by pushing some experimental commits to this PR. Or, I'd appreciate it if you could take the time to investigate it.

Sure, I can help you whenever you need a real macOS x86_64 environment. But my response is not very quick, so when in hurry it may be better just pushing a commit on this PR or other branches and see the result of GitHub action.

**Comment by akinomyoga** [comment]
@aiotter I found some strange behavior of the delay of `sleep` in the macOS testing environment. I would like to know whether this is specific to the testing environment or something universal in the macOS systems, so could you provide the result (`pr227.macos??.txt`) of the following script? You can put the text files as attached files in the reply.

```bash
$ cat pr227-measure.sh
#!/usr/bin/env bash

if [[ ${EPOCHREALTIME-} ]]; then
  measure() {
    local beg=$EPOCHREALTIME
    eval "$1"
    local end=$EPOCHREALTIME
    echo "$(bc -l <<< "$end-$beg") $2"
  }

else
  cc -o epoch.tmp -x c - <<EOF
#include <sys/time.h>
#include <stdio.h>
int main() {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  printf("%ld.%06u\n", tv.tv_sec, tv.tv_usec);
}
EOF

  chmod +x epoch.tmp
  measure() {
    local beg=$(./epoch.tmp)
    eval "$1"
    local end=$(./epoch.tmp)
    echo "$(bc -l <<< "$end-$beg") $2"
  }

  trap 'rm -f epoch.tmp' EXIT
  trap 'rm -f epoch.tmp; trap - INT; kill -INT $$' INT
fi

{
  echo "# $BASH_VERSION ($MACHTYPE)"
  for i in {0..100}; do
    measure ":"
  done
  for i in {0..100}; do
    measure "sleep 0.001" 0.001
  done
  for i in {2..300}; do
    printf -v v '0.%03d' "$i"
    measure "sleep $v" "$v"
  done
}
$ /path/to/bash-3.2 pr227-measure.sh > pr227.macos32.txt
$ /path/to/bash-5.x pr227-measure.sh > pr227.macos5x.txt  # if you have any bash 5.* (or bash 4.*)
```

**Comment by aiotter** [comment]
Hope this helps!
[pr227.macos32.txt](https://github.com/akinomyoga/ble.sh/files/9598212/pr227.macos32.txt)
[pr227.macos51.txt](https://github.com/akinomyoga/ble.sh/files/9598227/pr227.macos51.txt)

**Comment by akinomyoga** [comment]
Thank you for the data! It's not so obvious compared to the macOS in CI, but macOS seems to generally have some characteristic behavior in the delay in terminating the processes.

I have attached some plots: [pr227-sleep-delay.pdf](https://github.com/akinomyoga/ble.sh/files/9598337/pr227-sleep-delay.pdf)

- Page 1 is the scatter plot of the actual delay vs the argument specified to `sleep` command in the macOS of CI. A remarkable point is that it has extra random delay of 0--150 ms, whose distribution appears to be uniform. Another interesting observation is that when the requested delay specified to the `sleep` argument is less than 0.02 sec, the size of the random range is linear with respect to the requested delay.
- Page 2 shows the same plot in a wider range of the requested delay. The behavior is consistent for any requested delay larger than 0.02 sec.
- Page 3 is the histogram of the delay for `sleep 0.001`. This effectively measures the potential performance of spawning processes  in the system. We see a double peak structure, which is statistically significant.
- Page 4 shows the histogram of extra delay  for the sleep > 0.020. It's not actually uniform, but widely distributed in the range 0--0.150.
- Page 5-10 compares the scatter plot in different systems.
  - In GNU/Linux and Cygwin/Windows, the extra delay is constant with respect to the requested delay.
  - In FreeBSD, the extra delay seems to slightly increases as the requested delay does, but the amount of the increase is relatively negligible compared to the requested delay.
  - The macOS results are plotted by the data you provided (thank you!), where I observe the increase of the extra delay for the requested delay < 0.020, though I don't see the randomness we observed in the CI macOS.

I have checked [the source of sleep in macOS](https://github.com/apple-oss-distributions/shell_cmds/blob/main/sleep/sleep.c), where I don't find anything suspicious. I guess this strange behavior is related to the behavior of the task scheduler of macOS kernel.

A constant extra delay can be calibrated by subtracting the constant delay before passing the delay to `sleep 0.020`, but random delay cannot be calibrated. Also, the range of randomness, 150 ms, is too large. Even without the randomness, argument-dependent extra delay is hard to calibrate in the actual Bash sessions because it takes a too long time to measure the argument-dependent delay in a statistically reliable way in actual user sessions.

I think I'll just skip the test for the sleep delay in CI. I'll keep the tests in the other environment of macOS, though it might fail occasionally.

**Comment by akinomyoga** [comment]
A Bash bug found by `matrix.os = windows-latest`: [[PATCH] 4.3..devel: Fix printf %d "'X" affected by intermediate mbstate_](https://lists.gnu.org/archive/html/bug-bash/2022-09/msg00055.html)

**Comment by akinomyoga** [comment]
I finally merged it. Thank you!

**Pull request merged**
